config/routes.rb
Rails.application.routes.draw do
  resources :subtasks
  resources :tasks

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'tasks#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  validates :description, :task_id, presence: true
  #has_one :task
  belongs_to :task

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description,:user_id,  presence: true
  has_many :subtask, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_subtask, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @subtasks = Subtask.all
   # respond_with(@subtasks)
    respond_to do |format|
      format.html { @subtasks }
      format.json { render json: @subtasks}

    end
  end

  def show
    #respond_with(@subtask)
    respond_to do |format|
      format.html { @subtasks }
      format.json { render json: @subtasks }
    end
  end

  def new
    @subtask = Subtask.new
     respond_with(@subtask)
  end

  def create
    @subtask = Subtask.new(subtask_params)
    #@subtask.save
    #respond_with(@subtask)

    respond_to do |format|
      if @subtask.save
        format.html { redirect_to tasks_path, notice: 'Subtask was successfully created.' }
        #format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @subtask }
        format.js {@subtask}
      else
        format.html { render :new }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
        format.js
      end
    end

  end

  def update
    @subtask.update(subtask_params)
    respond_with(@subtask)
  end

  def destroy
    @subtask.destroy
    #respond_with(@subtask)

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Subtask was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end

  end

  private
    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    def subtask_params
      params.require(:subtask).permit(:description, :task_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index

    @tasks = Task.where(user_id: current_user.id)+(Task.where( public: true))
    @tasks.uniq!
    @subtask = Subtask.new
    @subtasks = Subtask.all

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id= current_user.id

    if not @task.public?
      @task.public = false
    else
      @task.public = true
    end

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        #format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update

    respond_to do |format|
      if @task.update(task_params) and has_permission?
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        flash[:error] = "You don't have permission to access" if not has_permission?

        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    if current_user.id == @task.user_id
      @task.destroy

      #TODO remove subtasks

      respond_to do |format|
        format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:error] = "You don't have permission to access"
      redirect_to tasks_url
    end
  end

  # HELPERS

  helper_method :substask_get, :has_permission?

  def has_permission?
    true if current_user.id == @task.user_id
  end

  def substask_get(id)
    @subtasks= Subtask.where(task_id: id)
    if @subtasks
      @subtasks
    else
      @subtasks= {}
    end
  end

  def has_permission?
    true if current_user.id == @task.user_id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :public, :id_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to( "tasks to do", tasks_path, class: 'navbar-brand' )%>

    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to( "Tasks", tasks_path )%></li>
        <li><%= link_to( "New Task", new_task_path )%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to(edit_user_registration_path) do %>
            <%= fa_icon "user lg", text: "User Edit".html_safe %>
          <%end %>
        </li>
        <li><%= link_to(destroy_user_session_path, method: 'delete') do %>
            <%= fa_icon "sign-out lg", text: "Sign Out".html_safe %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="container-fluid">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TASK MANAGER - Avenue Code</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= render 'layouts/header' %>
  <% end %>

  <%= render 'layouts/messages' %>

  <%= yield %>

  <%= yield :js %>
</body>
</html>

app/views/subtasks/_form.html.erb
<%= simple_form_for(@subtask) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :task_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary btn-block' %>
  </div>
<% end %>

app/views/subtasks/create.js.erb
$link_del = '<a data-confirm="Are you sure?" data-remote="true" rel="nofollow" data-method="delete" href="<%=subtask_path(@subtask)%>">  <i class="fa fa-trash"></i> </a> ';
$link_edit = '<a href="<%=edit_subtask_path(@subtask)%>"> <i class="fa fa-pencil-square"></i></a> '
$li = '<li '+'id="subtask_<%= @subtask.id %>" class="list-group-item"> ' +'<%=@subtask.description%>'+ $link_edit + $link_del +'</li>';
$('#task_<%=@subtask.task_id%>').append($li);
$('#input_task_<%=@subtask.task_id %>').val('');

app/views/subtasks/destroy.js.erb
$('#subtask_<%=@subtask.id%>').remove();

app/views/subtasks/edit.html.erb
<div class="form-signin">

  <h1>Editing Subtask</h1>

  <%= simple_form_for(@subtask) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :description %>
      <%#= f.input :task_father_id %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn-primary btn-block' %>
    </div>
  <% end %>


  <%#= link_to 'Show', @subtask %>
  <%= link_to 'Back', tasks_path %>

</div>

app/views/subtasks/index.html.erb
<div class="container">
<h1>Listing Subtasks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Task father</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subtasks.each do |subtask| %>
      <tr>
        <td><%= subtask.description %></td>
        <td><%= subtask.task_id %></td>
        <td><%= link_to 'Show', subtask %></td>
        <td><%= link_to 'Edit', edit_subtask_path(subtask) %></td>
        <td><%= link_to 'Destroy', subtask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subtask', new_subtask_path %>
</div>

app/views/subtasks/new.html.erb
<div class="form-signin">
  <h1>New Subtask</h1>

  <%= render 'form' %>

  <%= link_to 'Back', subtasks_path %>

</div>

app/views/subtasks/show.html.erb
<div class="form-signin">

  <p>
  <h1>Subtask Show</h1>
  <h2>Subtask: <%= @subtask.description %></h2>
  </p>



  <%#= link_to 'Edit', edit_subtask_path(@subtask) %>
  <%#= link_to 'Back', subtasks_path %>

</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%#= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%# f.input :user_id %>
    <%= f.input :public %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-default btn-primary btn-block' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="form-signin">

  <h1>Editing Task</h1>

  <%= render 'form' %>

  <%= link_to 'Back', tasks_path %>

</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2" >
      <h1>Listing Tasks</h1>
      <%= link_to 'New Task', new_task_path, class: "btn btn-default btn-primary btn-add-new-task" %>
        <ul class="list-group">
          <% @tasks.each do |t| %>
            <li class="list-group-item">
              <h3> <%= if t.public == true then fa_icon "user" else fa_icon "users" end%> <%= t.description %></h3>
              <%= link_to 'Edit', edit_task_path(t) if t.user_id == current_user.id  %> <%= '/' if t.user_id == current_user.id %>
              <%= link_to 'Destroy', t, method: :delete, data: { confirm: 'Are you sure?' } if t.user_id == current_user.id  %>
            </li>
            <li class="list-group-item">
              <% if t.user_id == current_user.id %>
                  <%= simple_form_for @subtask, :html => { :class => 'form-inline' }, remote: true, validate:true  do |f| %>
                    <div class="form-group">
                       <%= f.input :description, label: false, class: 'form-control',  input_html: {id: "input_task_#{t.id}"}, required: true %>
                       <%= f.hidden_field :task_id, value: t.id %>
                    </div>
                    <button type="submit" class="btn btn-default">New Subtask</button>
                  <% end %><br>
              <% end %>
              <%= substask_get(t.id).length >= 0 ? "<ul id='task_#{t.id}' class='list-group'>".html_safe : ''  %>
              <% substask_get(t.id).each do |s| %>
                <li id="subtask_<%= s.id %>" class="list-group-item">
                  <%= s.description %>
                  <% if t.user_id == current_user.id %>
                    <%= link_to( edit_subtask_path(s)) do%>
                      <%= fa_icon "pencil-square"%>
                    <%end%>
                    <%= link_to(subtask_path(s), method: :delete, remote: true, data: { confirm: 'Are you sure?' }  ) do%>
                      <%= fa_icon "trash"%>
                    <%end%>
                  <% end %>
                </li>
               <% end %>
              <%= substask_get(t.id).length >= 0 ? ' </ul>'.html_safe : ''  %>
            <% end %>
        </ul>
    </div>
  </div>
</div> <br><br><br>

<% content_for :js do %>

<% end %>

app/views/tasks/new.html.erb
<div class="form-signin">

  <h1>New Task</h1>

  <%= render 'form' %>

  <%= link_to 'Back', tasks_path %>

</div>

app/views/tasks/show.html.erb
<div class="form-signin">

  <div class="form-signin">

  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>User owner:</strong>
    <%= @task.user_id %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= @task.public %>
  </p>

  <%= link_to 'Edit', edit_task_path(@task) %> <br>
  <%= link_to 'Back', tasks_path %>
  </div>
</div>